name: Create an archetype

on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate project
        run:  |
          mvn archetype:generate "-DarchetypeGroupId=my.groupId" "-DarchetypeArtifactId=my-archetype-id" "-DarchetypeVersion=1.3" "-DgroupId=my.groupID" "-DartifactId=createdArtifact" -s .\settings.xml
