name: Create an archetype

on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Generate project
        run:  |
          ls .github/workflows/
          pwd
          mvn archetype:generate "-DarchetypeGroupId=my.groupId" "-DarchetypeArtifactId=my-archetype-id" "-DarchetypeVersion=1.3" "-DgroupId=my.groupID" "-DartifactId=createdArtifact" -s ./.github/workflows/settings.xml -X
