name: Init Project

on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCHETYPE_GROUP_ID: "com.google.code.plsqlmaven"
      ARCHETYPE_ARTIFACT_ID: "plsql-project-archetype"
      ARCHETYPE_VERSION: "1.11"
      GROUP_ID: "my.groupId"
      ARTIFACT_ID: "test-create-archetype"
      VERSION: "1.0.0"
    steps:
      - name: Do not run on template repository
        shell: bash
        run: |
          curl --silent -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.baptiste-preview+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq --exit-status '.is_template == false';
            
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Generate project
        run:  |
          mvn archetype:generate -B \
            -DarchetypeGroupId=$ARCHETYPE_GROUP_ID \
            -DarchetypeArtifactId=$ARCHETYPE_ARTIFACT_ID \
            -DarchetypeVersion=$ARCHETYPE_VERSION \
            -DgroupId=$GROUP_ID \
            -DartifactId=$ARTIFACT_ID \
            -Dversion=$VERSION

      - name: Git Commit/Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          rm .github/workflows/init.yml
          cd test-create-archetype/
          mv * ../
          cd ..
          rmdir test-create-archetype/
          git add .
          git commit -m "initial commit"
          git push origin main -f
          git checkout -b test main
          git checkout -b develop main
          git push --all -u

      - name: Create empty secrets for repository
        run: |
          declare -a env_vars=(AWS_KEY AWS_SECRET GHA_PAT IMG_S3_ACCESS_KEY IMG_S3_BUCKET IMG_S3_REGION IMG_S3_SECRET_KEY JWT_API_KEY, SECRET_KEY SPRING_DATASOURCE_PASSWORD SPRING_DATASOURCE_URL SPRING_DATASOURCE_USERNAME)
          for i in "${env_vars[@]}"
          do
            echo "$i"
            curl \
            -u akeem35:${{ secrets.PAT_TOKEN }} \
            -X PUT \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/akeem35/template_maven_api/actions/secrets/$i \
            -d '{"encrypted_value":""}'
          done
