name: Init Project

on: 
  push:
    paths:
      - .github/workflows/init.yml


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCHETYPE_GROUP_ID: ""
      ARCHETYPE_ARTIFACT_ID: ""
      ARCHETYPE_VERSION: ""
      GROUP_ID: ""
      ARTIFACT_ID: ""
      VERSION: ""
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Generate project
        run:  |
          mvn archetype:generate -B \
            -DarchetypeGroupId="com.google.code.plsqlmaven" \
            -DarchetypeArtifactId="plsql-project-archetype" \
            -DarchetypeVersion="1.11" \
            -DgroupId="my.groupId" \
            -DartifactId=test-create-archetype 
            -Dversion="1.0.0" 

      - name: Git Commit/Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          cd test-create-archetype/
          mv * ../
          cd ..
          rmdir test-create-archetype/
          git add .
          git commit -m "initial commit"
          git push origin main -f
