name: Init Project

on: create


jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Generate project
        run:  mvn archetype:generate -DarchetypeGroupId="com.google.code.plsqlmaven" -DarchetypeArtifactId="plsql-project-archetype" -DarchetypeVersion="1.11" -DgroupId="my.groupId" -DartifactId=test-create-archetype -Dversion="1.0.0" -B

      - name: Git Commit/Push Changes
        run: |
          git commit -m "initial commit"
          git push origin main -f