name: Build, Unit-test, SCA

on:
  pull_request:
    types:
      - opened
    branches:
      - 'feature/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  unit-test:
    name: Build, Unit-test, SCA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-v1-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-v1

      - name: Maven Resolve Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mvn dependency:go-offline -e

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-v1
          restore-keys: ${{ runner.os }}-sonar-v1
      
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
